const AUTH_CHALLENGE_EXPIRATION = 1000 * 60 * 2;
const JTI_VALIDITY_WINDOW_MS = 1000 * 60 * 4;
const DPOP_IAT_VALIDITY_WINDOW_S = 60 * 3;

export {
  AUTH_CHALLENGE_EXPIRATION,
  JTI_VALIDITY_WINDOW_MS,
  DPOP_IAT_VALIDITY_WINDOW_S,
};
